version: "1"
services:

  mysql_db:
    image: mysql:8.0
    restart: always

    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=crud_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=test
    ports:
      - '3306:3306'

  app:
    build: .
    restart: on-failure
    ports:
      - '8080:8080'
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/crud_db
    depends_on:
      - mysql_db


