spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    username: root
    password: test
    url: jdbc:mysql://localhost:3306/mydb

#validation:
  #max-age: 100