spring:
  liquibase:
    clear-checksums: true
    change-log: db/changelog/changelog.yaml
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: test
    url: jdbc:mysql://localhost:3306/crud_db
