#dev environment
---
spring:
  liquibase:
    user: root
    password: test
    url: jdbc:mysql://localhost:3306/crud_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    clear-checksums: true
    change-log: db/changelog/changelog.yaml
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
    hibernate:
      ddl-auto: none

  datasource:
    username: root
    password: test
    url: jdbc:mysql://localhost:3306/crud_db?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver


#test environment
---
spring:
  config:
    activate:
      on-profile: test
  liquibase:
    clear-checksums: true
    change-log: db/changelog/changelog.yaml
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    database: h2
    hibernate:
      ddl-auto: none
  datasource:
    username: root
    password: test
    url: jdbc:h2:mem:test_db;MODE=MySQL